<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app.js',
                'http://localhost:8080/build/app.js',
            ],
        ],
    ],
],

]];
